/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SATS_Bakery;


import model.Cake;
import dao.CakeDao;
import java.awt.Color;
import java.util.Iterator;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author POULAMI
 */
public class CakeCustomization extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProduct
     */
    public CakeCustomization() {
        initComponents();
        btnsave.setEnabled(true);
        
    }
    
    public void validateFields(){
        String flavour = txtflavour.getText();
        String price = txtprice1.getText();
        if(!flavour.equals("") && !price.equals(""))
            btnsave.setEnabled(false);
        else
            btnsave.setEnabled(true);
        
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Color = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtflavour = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        txtshape = new javax.swing.JTextField();
        txtmobilenumber = new javax.swing.JTextField();
        txtnameoncake = new javax.swing.JTextField();
        txtallergetic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtdod = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtocassion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtegg = new javax.swing.JTextField();
        lblimage = new javax.swing.JLabel();
        txtweight = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtprice1 = new javax.swing.JTextField();
        txtcustomername = new javax.swing.JTextField();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.01.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 134));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        jLabel1.setText("Customize Your Cake");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Flavour");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        Color.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Color.setText("Color");
        getContentPane().add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Name on the Cake");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        txtflavour.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtflavour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtflavourKeyReleased(evt);
            }
        });
        getContentPane().add(txtflavour, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 320, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, -1));

        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtcolor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtcolor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcolorKeyReleased(evt);
            }
        });
        getContentPane().add(txtcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 320, -1));

        txtshape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtshape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtshapeKeyReleased(evt);
            }
        });
        getContentPane().add(txtshape, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 320, -1));

        txtmobilenumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtmobilenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmobilenumberKeyReleased(evt);
            }
        });
        getContentPane().add(txtmobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 210, -1));

        txtnameoncake.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnameoncake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameoncakeKeyReleased(evt);
            }
        });
        getContentPane().add(txtnameoncake, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 370, -1));

        txtallergetic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtallergetic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtallergeticKeyReleased(evt);
            }
        });
        getContentPane().add(txtallergetic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 320, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Weight(kg)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Shape");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Allergetic");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Egg or Eggless");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtdod.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdod.setToolTipText("yyyy/mm/dd");
        txtdod.setActionCommand("yyyy/mm/dd");
        txtdod.setName("yyyy/mm/dd"); // NOI18N
        txtdod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdodActionPerformed(evt);
            }
        });
        txtdod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdodKeyReleased(evt);
            }
        });
        getContentPane().add(txtdod, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 270, -1));
        txtdod.getAccessibleContext().setAccessibleName("");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Date to Deliver");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        txtocassion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtocassion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtocassionKeyReleased(evt);
            }
        });
        getContentPane().add(txtocassion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 320, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Ocassion");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Price");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        txtegg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtegg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txteggKeyReleased(evt);
            }
        });
        getContentPane().add(txtegg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 320, -1));

        lblimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        txtweight.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtweight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtweightKeyReleased(evt);
            }
        });
        getContentPane().add(txtweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 320, -1));

        label1.setForeground(new java.awt.Color(255, 0, 0));
        label1.setText("* yyyy/mm/dd");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Contact Us : 8618517435");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 220, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Customer Name");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Mobile Number");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        txtprice1.setEditable(false);
        txtprice1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtprice1.setText("400");
        txtprice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprice1ActionPerformed(evt);
            }
        });
        txtprice1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprice1KeyReleased(evt);
            }
        });
        getContentPane().add(txtprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 320, -1));

        txtcustomername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtcustomername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcustomernameKeyReleased(evt);
            }
        });
        getContentPane().add(txtcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
       String mobilenumber = txtmobilenumber.getText();
        if(mobilenumber.matches("^[0-9]*$") && mobilenumber.length()==10)
        {
            JOptionPane.showMessageDialog(null,"correct mobile number");
            Cake product = new Cake();
        product.setFlavour(txtflavour.getText());
        product.setColor(txtcolor.getText());
        product.setPrice(txtprice1.getText());
        product.setAllergetic(txtallergetic.getText());
        product.setShape(txtshape.getText());
        product.setWeight(txtweight.getText());
        product.setEggoreggless(txtegg.getText());
        product.setNameoncake(txtnameoncake.getText());
        product.setDod(txtdod.getText());
        product.setOcassion(txtocassion.getText());
        product.setCustomername(txtcustomername.getText());
        product.setMobilenumber(txtmobilenumber.getText());
        CakeDao.save(product);
        setVisible(false);
        new CakeCustomization().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"incorrect mobile number");
        }
        
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtflavourKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtflavourKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtflavourKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CakeCustomization().setVisible(true);
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtcolorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcolorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcolorKeyReleased

    private void txtshapeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtshapeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtshapeKeyReleased

    private void txtmobilenumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobilenumberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobilenumberKeyReleased

    private void txtnameoncakeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameoncakeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameoncakeKeyReleased

    private void txtallergeticKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtallergeticKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtallergeticKeyReleased

    private void txtdodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdodKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdodKeyReleased

    private void txtocassionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtocassionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtocassionKeyReleased

    private void txteggKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteggKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txteggKeyReleased

    private void txtweightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtweightKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtweightKeyReleased

    private void txtdodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdodActionPerformed

    private void txtprice1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprice1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprice1KeyReleased

    private void txtcustomernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustomernameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomernameKeyReleased

    private void txtprice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprice1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CakeCustomization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CakeCustomization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CakeCustomization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CakeCustomization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CakeCustomization().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Color;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label label1;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTextField txtallergetic;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtcustomername;
    private javax.swing.JTextField txtdod;
    private javax.swing.JTextField txtegg;
    private javax.swing.JTextField txtflavour;
    private javax.swing.JTextField txtmobilenumber;
    private javax.swing.JTextField txtnameoncake;
    private javax.swing.JTextField txtocassion;
    private javax.swing.JTextField txtprice1;
    private javax.swing.JTextField txtshape;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
